//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalTask
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string InputData { get; set; }
        public string OutputData { get; set; }
        public string ExternalId { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
        public virtual User Worker { get; set; }
        public virtual ExternalTaskType ExternalTaskType { get; set; }
        public virtual WorkflowInstance WorkflowInstance { get; set; }
    }
}
