//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Topic { get; set; }
        public string Body { get; set; }
        public string Locale { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual User From { get; set; }
        public virtual User To { get; set; }
    }
}
