//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowInstance()
        {
            this.Bookmarks = new HashSet<Bookmark>();
            this.ExternalTasks = new HashSet<ExternalTask>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid InstanceId { get; set; }
        public string ExternalId { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public FlowBot.Common.Models.WorkflowInstanceStates State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual Conversation Conversation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalTask> ExternalTasks { get; set; }
    }
}
